### PR TITLE
rosbag for windows

### PR DESCRIPTION
**Pull request by predrag12**
You only need the latest commit, please ignore the other two (GitHub artifacts).

### CODE REVIEW

**Comment by stonier** [comment]
Couldn't pull this one directly as some parts of the patch are confused.

I pulled in some of the .gitignore and .gitattributes to win_ros - they were useful to me. I hadn't done anything with .gitattributes before.

The patch itself though - is the wrong way around (order reversed) and seems to be missing alot. Did you diff against a clean source tree?

At any rate, I found the stdin code you inserted. I'll see if I can bugfix my rosplay here and then try your code.

**Comment by predrag12** [comment]
I sent you another pull request with the correct direction, you may need to adjust some of the declares to go into macros.h and add rosbag to the cmake_install.cmake.  I think most of the code changes are there, where do you have the 
compilation errors occur and is it on Win7 or the cross-compiler?

-Predrag

**Comment by stonier** [comment]
No problems compiling. See separate email. I brought in the windows code and got it compiling but, like you previously mentioned, something else was eating the keyboard input. 

So I checked the case when running play.exe directly. It worked fine. Then went and bugfixed the python rosbag calling code to ensure stdin was passed correctly to the subprocess. Presto!

Will clean it all up tonight, see if I can get the other rosbag commands working properly as well (more python fixes needed there).

**Comment by stonier** [comment]
Thanks for the windows console code!

**Comment by stonier** [comment]
Latest commits fix pretty much everything in rosbag
- Your console code from above is in.
- Boost filesystem code to check for disk drive space.
- Boost date_time code for cross platform time signatures.
- Fixed some warnings to deprecating code.
- Fixed an issue in genpy so that 'rosbag compress' works on windows.

Bundling a new sdk now (0.12.0). Moving on!

**Pull request closed without merging**
